"""mission 021: learning paths, opportunities, experiences, applications

Revision ID: 0002_mission021
Revises: 0001_baseline
Create Date: 2026-08-29 21:24:41.666417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_mission021'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('actions', sa.Text(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('technologies', sa.Text(), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=False),
    sa.Column('demo_url', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiences_experience_type'), ['experience_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiences_id'), ['id'], unique=False)

    op.create_table('learning_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_paths_id'), ['id'], unique=False)

    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_external_id', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('employment_type', sa.String(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('legacy_job_id', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['legacy_job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_job_id'),
    sa.UniqueConstraint('source', 'source_external_id', name='uq_opportunity_source_external_id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_opportunity_type'), ['opportunity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_source'), ['source'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('legacy_job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('job_analysis', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['legacy_job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_legacy_job_id'), ['legacy_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)

    op.create_table('experience_skills',
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('experience_id', 'skill_id')
    )
    op.create_table('learning_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learning_path_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learning_path_id', 'position', name='uq_learning_step_path_position')
    )
    with op.batch_alter_table('learning_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_steps_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_steps_learning_path_id'), ['learning_path_id'], unique=False)

    op.create_table('portfolio_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('actions', sa.Text(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('technologies', sa.Text(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=False),
    sa.Column('demo_url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_entries_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_entries_project_id'), ['project_id'], unique=False)

    op.create_table('application_experience_matches',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.PrimaryKeyConstraint('application_id', 'experience_id')
    )
    op.create_table('cover_letter_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('character_limit', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'position', name='uq_cover_letter_question_application_position')
    )
    with op.batch_alter_table('cover_letter_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cover_letter_questions_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cover_letter_questions_id'), ['id'], unique=False)

    op.create_table('learning_step_resources',
    sa.Column('learning_step_id', sa.Integer(), nullable=False),
    sa.Column('learning_resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['learning_resource_id'], ['learning_resources.id'], ),
    sa.ForeignKeyConstraint(['learning_step_id'], ['learning_steps.id'], ),
    sa.PrimaryKeyConstraint('learning_step_id', 'learning_resource_id')
    )
    op.create_table('cover_letter_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('draft', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['cover_letter_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'version', name='uq_cover_letter_answer_question_version')
    )
    with op.batch_alter_table('cover_letter_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cover_letter_answers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cover_letter_answers_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cover_letter_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cover_letter_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_cover_letter_answers_id'))

    op.drop_table('cover_letter_answers')
    op.drop_table('learning_step_resources')
    with op.batch_alter_table('cover_letter_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cover_letter_questions_id'))
        batch_op.drop_index(batch_op.f('ix_cover_letter_questions_application_id'))

    op.drop_table('cover_letter_questions')
    op.drop_table('application_experience_matches')
    with op.batch_alter_table('portfolio_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_entries_project_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_entries_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_entries_experience_id'))

    op.drop_table('portfolio_entries')
    with op.batch_alter_table('learning_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_steps_learning_path_id'))
        batch_op.drop_index(batch_op.f('ix_learning_steps_id'))

    op.drop_table('learning_steps')
    op.drop_table('experience_skills')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_applications_legacy_job_id'))
        batch_op.drop_index(batch_op.f('ix_applications_id'))

    op.drop_table('applications')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_source'))
        batch_op.drop_index(batch_op.f('ix_opportunities_opportunity_type'))
        batch_op.drop_index(batch_op.f('ix_opportunities_id'))

    op.drop_table('opportunities')
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_paths_id'))

    op.drop_table('learning_paths')
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiences_id'))
        batch_op.drop_index(batch_op.f('ix_experiences_experience_type'))

    op.drop_table('experiences')
    # ### end Alembic commands ###
