"""mission 023: opportunity skills, match score, market snapshots

Revision ID: 0004_mission023
Revises: 0003_mission022
Create Date: 2026-09-02 11:15:48.243985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004_mission023'
down_revision: Union[str, Sequence[str], None] = '0003_mission022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_count', sa.Integer(), nullable=False),
    sa.Column('total_opportunities', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_snapshots_skill_id'), ['skill_id'], unique=False)

    op.create_table('opportunity_skills',
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('opportunity_id', 'skill_id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('match_recommendation', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('scored_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_column('scored_at')
        batch_op.drop_column('match_recommendation')
        batch_op.drop_column('match_score')

    op.drop_table('opportunity_skills')
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_snapshots_skill_id'))
        batch_op.drop_index(batch_op.f('ix_market_snapshots_id'))
        batch_op.drop_index(batch_op.f('ix_market_snapshots_captured_at'))

    op.drop_table('market_snapshots')
    # ### end Alembic commands ###
