"""phase 1: target career

Revision ID: 0005_target_career
Revises: 0004_mission023
Create Date: 2026-09-06 21:14:55.024230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005_target_career'
down_revision: Union[str, Sequence[str], None] = '0004_mission023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_careers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('target_careers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_target_careers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_careers_is_active'), ['is_active'], unique=False)

    op.create_table('target_career_skills',
    sa.Column('target_career_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['target_career_id'], ['target_careers.id'], ),
    sa.PrimaryKeyConstraint('target_career_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_career_skills')
    with op.batch_alter_table('target_careers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_target_careers_is_active'))
        batch_op.drop_index(batch_op.f('ix_target_careers_id'))

    op.drop_table('target_careers')
    # ### end Alembic commands ###
