"""phase 1: daily plan tasks

Revision ID: 0006_today_plan
Revises: 0005_target_career
Create Date: 2026-09-06 22:12:59.758217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006_today_plan'
down_revision: Union[str, Sequence[str], None] = '0005_target_career'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_plan_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('carried_from', sa.Date(), nullable=True),
    sa.Column('learning_step_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('learning_resource_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['learning_resource_id'], ['learning_resources.id'], ),
    sa.ForeignKeyConstraint(['learning_step_id'], ['learning_steps.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_plan_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_plan_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_plan_tasks_plan_date'), ['plan_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_plan_tasks_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_plan_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_plan_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_daily_plan_tasks_plan_date'))
        batch_op.drop_index(batch_op.f('ix_daily_plan_tasks_id'))

    op.drop_table('daily_plan_tasks')
    # ### end Alembic commands ###
