"""phase 1: remember plan settings

Revision ID: 0007_plan_settings
Revises: 0006_today_plan
Create Date: 2026-09-06 22:19:00.382168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007_plan_settings'
down_revision: Union[str, Sequence[str], None] = '0006_today_plan'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_plan_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_available_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plan_intensity', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_plan_tasks', schema=None) as batch_op:
        batch_op.drop_column('plan_intensity')
        batch_op.drop_column('plan_available_minutes')

    # ### end Alembic commands ###
