"""phase 2: my learning library

Revision ID: 0008_library
Revises: 0007_plan_settings
Create Date: 2026-09-06 22:24:11.080077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008_library'
down_revision: Union[str, Sequence[str], None] = '0007_plan_settings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_resource_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learning_resource_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('start_ref', sa.Integer(), nullable=True),
    sa.Column('end_ref', sa.Integer(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learning_resource_id'], ['learning_resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learning_resource_id', 'position', name='uq_segment_resource_position')
    )
    with op.batch_alter_table('learning_resource_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_resource_segments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_resource_segments_learning_resource_id'), ['learning_resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_resource_segments_status'), ['status'], unique=False)

    with op.batch_alter_table('learning_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ownership', sa.String(), server_default='saved', nullable=False))
        batch_op.add_column(sa.Column('total_units', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_label', sa.String(), server_default='', nullable=False))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_learning_resources_ownership'), ['ownership'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_resources_ownership'))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('unit_label')
        batch_op.drop_column('total_units')
        batch_op.drop_column('ownership')

    with op.batch_alter_table('learning_resource_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_resource_segments_status'))
        batch_op.drop_index(batch_op.f('ix_learning_resource_segments_learning_resource_id'))
        batch_op.drop_index(batch_op.f('ix_learning_resource_segments_id'))

    op.drop_table('learning_resource_segments')
    # ### end Alembic commands ###
