"""phase 4: project evidence fields

Revision ID: 0010_evidence
Revises: 0009_effort
Create Date: 2026-09-06 22:52:52.843917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0010_evidence'
down_revision: Union[str, Sequence[str], None] = '0009_effort'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_bullet', sa.Text(), server_default='', nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_url', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('demo_url', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('results', sa.Text(), server_default='', nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('results')
        batch_op.drop_column('demo_url')
        batch_op.drop_column('github_url')

    with op.batch_alter_table('portfolio_entries', schema=None) as batch_op:
        batch_op.drop_column('resume_bullet')

    # ### end Alembic commands ###
