"""phase 5.6: calendar

Revision ID: 0012_calendar
Revises: 0011_profile
Create Date: 2026-09-07 12:47:16.284791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0012_calendar'
down_revision: Union[str, Sequence[str], None] = '0011_profile'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_blocks_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_blocks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_blocks_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_blocks_weekday'), ['weekday'], unique=False)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_start_minute', sa.Integer(), server_default='540', nullable=False))
        batch_op.add_column(sa.Column('day_end_minute', sa.Integer(), server_default='1320', nullable=False))
        batch_op.add_column(sa.Column('daily_cap_minutes', sa.Integer(), server_default='180', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('daily_cap_minutes')
        batch_op.drop_column('day_end_minute')
        batch_op.drop_column('day_start_minute')

    with op.batch_alter_table('calendar_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_blocks_weekday'))
        batch_op.drop_index(batch_op.f('ix_calendar_blocks_kind'))
        batch_op.drop_index(batch_op.f('ix_calendar_blocks_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_blocks_date'))

    op.drop_table('calendar_blocks')
    # ### end Alembic commands ###
