"""plan task opportunity

Revision ID: 0015_plan_opp
Revises: 0014_aliases
Create Date: 2026-09-08 12:43:16.393271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0015_plan_opp'
down_revision: Union[str, Sequence[str], None] = '0014_aliases'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite 는 이름 없는 제약을 배치 변경으로 만들지 못한다.
    with op.batch_alter_table('daily_plan_tasks', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('opportunity_id', sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            'fk_daily_plan_tasks_opportunity_id',
            'opportunities',
            ['opportunity_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_plan_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_daily_plan_tasks_opportunity_id', type_='foreignkey'
        )
        batch_op.drop_column('opportunity_id')

    # ### end Alembic commands ###
