"""skill level history

Revision ID: 0016_skill_level
Revises: 0015_plan_opp
Create Date: 2026-09-10 13:57:55.498205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0016_skill_level'
down_revision: Union[str, Sequence[str], None] = '0015_plan_opp'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_level_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('from_level', sa.Integer(), nullable=False),
    sa.Column('to_level', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), server_default='manual', nullable=False),
    sa.Column('note', sa.String(), server_default='', nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_level_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_level_events_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_level_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_level_events_skill_id'), ['skill_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_level_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_level_events_skill_id'))
        batch_op.drop_index(batch_op.f('ix_skill_level_events_id'))
        batch_op.drop_index(batch_op.f('ix_skill_level_events_changed_at'))

    op.drop_table('skill_level_events')
    # ### end Alembic commands ###
