"""profile and experience links

Revision ID: 0017_links
Revises: 0016_skill_level
Create Date: 2026-09-15 15:24:32.038755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0017_links'
down_revision: Union[str, Sequence[str], None] = '0016_skill_level'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blog_url', sa.String(), server_default='', nullable=False))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_url', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('blog_url', sa.String(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('blog_url')
        batch_op.drop_column('github_url')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_column('blog_url')

    # ### end Alembic commands ###
